<?php


// Translation of file /modules/gallery/module.php

$_COS_LANG_MODULE['View gallery'] = 'Vis galleri';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Upload image'] = 'Upload Billed';
$_COS_LANG_MODULE['File deleted'] = 'File deleted';
$_COS_LANG_MODULE['File is gallery default'] = 'Billedet er primært i gallery';
$_COS_LANG_MODULE['File added'] = 'Til tilføjet';
$_COS_LANG_MODULE['Could not rename file. File name already exists'] = 'Kunne ikke omdøbe fil. Fil med navn eksisterer';

// Translation of file /modules/gallery/upload/index.php

$_COS_LANG_MODULE['Upload zip file'] = 'Upload zip fil';
$_COS_LANG_MODULE['Rename files after following title'] = 'Omdøb filer efter følgende titel';
$_COS_LANG_MODULE['Could not move files'] = 'Kunne ikke flytte filer';
$_COS_LANG_MODULE['Could not set correct permissions on files'] = 'Kunne ikke ændre rettigheder';
$_COS_LANG_MODULE['Could not rename files'] = 'Kunne ikke ændre fil navne';
$_COS_LANG_MODULE['Could not commit to database'] = 'Kunne ikke commite til database';
$_COS_LANG_MODULE['Zip archive uploaded'] = 'Zip arkiv uploadet';

// Translation of file /modules/gallery/index.php

$_COS_LANG_MODULE['List galleries'] = 'Vis Gallerier';

// Translation of file /modules/gallery/admin/module.php

$_COS_LANG_MODULE['Gallery title should be at least 3 chars long'] = 'Galleriet titel skal mindst være tre karakterer';
$_COS_LANG_MODULE['Edit files'] = 'Ret billeder';
$_COS_LANG_MODULE['Edit gallery'] = 'Ret galleri';
$_COS_LANG_MODULE['Delete gallery'] = 'Slet galleri';
$_COS_LANG_MODULE['Main image'] = 'Primært';
$_COS_LANG_MODULE['No title'] = 'Ingen titel';
$_COS_LANG_MODULE['Set image details'] = 'Ændr billedets detaljer';
$_COS_LANG_MODULE['File name'] = 'Ændr fil navn';

// Translation of file /modules/gallery/admin/index.php

$_COS_LANG_MODULE['Gallery created'] = 'Nyt galleri oprettet';

// Translation of file /modules/gallery/admin/edit.php

$_COS_LANG_MODULE['Gallery updated'] = 'Galleri opdateret';

// Translation of file /modules/gallery/admin/delete.php

$_COS_LANG_MODULE['Gallery has been deleted'] = 'Galleri er blevet slettet';

// Translation of file /modules/gallery/inline/module.php

$_COS_LANG_MODULE['Large image'] = 'Stort billede';
$_COS_LANG_MODULE['Image details (exif)'] = 'Vis detaljer';
$_COS_LANG_MODULE['GPS'] = 'Vis kort';
$_COS_LANG_MODULE['Edit image details'] = 'Ret billiede';
$_COS_LANG_MODULE['Original image'] = 'Se originalt billede';
$_COS_LANG_MODULE['Image details has been updated'] = 'Detaljer opdateret!';

// Translation of file /modules/gallery/tags.php

$_COS_LANG_MODULE['Gallery tag'] = 'Galleri tag';

// Translation of file /modules/gallery/delete.php

$_COS_LANG_MODULE['Delete image'] = 'Delete image';
