<?php

/**
 * language file for module simple
 * included when module is being used
 *
 * @package simple
 */

$_COS_LANG_MODULE['Select Gallery'] = 'Vælg galleri';
$_COS_LANG_MODULE['Listing Galleries'] = 'Viser gallerier';
$_COS_LANG_MODULE['Add File'] = 'Nyt billede';
$_COS_LANG_MODULE['Title'] = 'Titel';

$_COS_LANG_MODULE['Add Gallery'] = 'Nyt Galleri';
$_COS_LANG_MODULE['View Galleries'] = 'Vis Gallerier';

$_COS_LANG_MODULE['Gallery title should be at least 3 chars long'] =
    'Galleriet titel skal mindst være tre karakterer';

$_COS_LANG_MODULE['List Galleries'] = 'Vis Gallerier';
$_COS_LANG_MODULE['Delete current image Admin?'] = 
    'Slet nuværende billede?';
$_COS_LANG_MODULE['View and Delete image by image'] =
    'Vis og slet billeder';

$_COS_LANG_MODULE['Edit gallery name'] = 'Rediger galleri navn';
$_COS_LANG_MODULE['Delete entire gallery'] = 'Slet galleri';
$_COS_LANG_MODULE['View this gallery'] = 'Vis dette gallery';
$_COS_LANG_MODULE['Edit this gallery'] = 'Rediger dette galleri';
$_COS_LANG_MODULE['No file specified'] = 'Ingen fil specificeret';
$_COS_LANG_MODULE['Gallery updated'] = 'Galleri opdateret';

$_COS_LANG_MODULE['Edit Gallery'] = 'Rediger gallery';
$_COS_LANG_MODULE['View gallery'] = 'Vis galleri';
$_COS_LANG_MODULE['Gallery created'] = 'Nyt galleri oprettet';

$_COS_LANG_MODULE['Upload image'] = 'Upload Billed';

$_COS_LANG_MODULE['File seems to already exist. Only unique filenames allowed'] =
    'File eksisterer. Kun unikke filnavne er tilladte.';
$_COS_LANG_MODULE['Edit gallery'] = 'Edit gallery';
$_COS_LANG_MODULE['gallery_edit_files'] = 'Ret billeder';
$_COS_LANG_MODULE['gallery_edit_name'] = 'Ret galleri';
$_COS_LANG_MODULE['gallery_form_title'] = 'Titel';
$_COS_LANG_MODULE['gallery_submit_title'] = 'gallery_submit_title';
$_COS_LANG_MODULE['Delete Gallery'] = 'Delete Gallery';
$_COS_LANG_MODULE['has been deleted'] = 'has been deleted';
$_COS_LANG_MODULE['File specified is to big'] = 'File specified is to big';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['gallery_file_deleted'] = 'Fil Slettet';
$_COS_LANG_MODULE['gallery_file_added'] = 'Til tilføjet';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['File deleted'] = 'File deleted';
$_COS_LANG_MODULE['gallery_default_image'] = 'Primært';

$_COS_LANG_MODULE['gallery_form_label_path'] = 'Intast en fysisk sti. Fx /billeder/by/natur';
$_COS_LANG_MODULE['gallery_file_is_default'] = 'Billedet er primært i gallery';

$_COS_LANG_MODULE['gallery_delete_has_files'] = 'Kan ikke slette galleri da der stadig er filer i det. Slet disse først.';
$_COS_LANG_MODULE['gallery_delete_legend'] = 'Slet galleri';


$_COS_LANG_MODULE['gallery_gallery_has_been_deleted'] = 'Galleri er blevet slettet';

$_COS_LANG_MODULE['gallery_delete_gallery'] = 'Slet galleri';

$_COS_LANG_MODULE['gallery_upload_zip_legend'] = 'Upload zip fil';
$_COS_LANG_MODULE['gallery_label_zip_add_chars'] = 'Omdøb filer efter følgende titel';
$_COS_LANG_MODULE['gallery_error_zip_mv'] = 'Kunne ikke flytte filer';
$_COS_LANG_MODULE['gallery_error_zip_chmod'] = 'Kunne ikke ændre rettigheder';
$_COS_LANG_MODULE['galler_error_unzip'] = 'Kunne ikke unzippe';
$_COS_LANG_MODULE['gallery_zip_could_not_rename_file'] = 'Kunne ikke ændre fil navne';
$_COS_LANG_MODULE['gallery_zip_error_scale'] = 'Skalerings fejl';
$_COS_LANG_MODULE['gallery_zip_mv_error'] = 'Kunne ikke flytte filer';
$_COS_LANG_MODULE['gallery_zip_commit_error'] = 'Kunne ikke commite til database';
$_COS_LANG_MODULE['gallery_zip_archive_uploaded'] = 'Zip arkiv uploadet';
$_COS_LANG_MODULE['gallery_set_image_details'] = 'Ændr billedets detaljer';
$_COS_LANG_MODULE['gallery_file_name'] = 'Ændr fil navn';
$_COS_LANG_MODULE['gallery_view_full_size'] = 'Original billide';
$_COS_LANG_MODULE['gallery_image_details_updated'] = 'Detaljer opdateret!';

$_COS_LANG_MODULE['gallery_tags_list_entries_title'] = 'Galleri tag';
$_COS_LANG_MODULE['gallery_could_not_rename_file_exists'] = 'Kunne ikke omdøbe fil. Fil med navn eksisterer';
