<?php

/**
 * language file for module simple
 * included when module is being used
 *
 * @package simple
 */

$_COS_LANG_MODULE['Select Gallery'] = 'Vælg galleri';
$_COS_LANG_MODULE['Listing Galleries'] = 'Viser gallerier';
$_COS_LANG_MODULE['Add File'] = 'Nyt billede';
$_COS_LANG_MODULE['Title'] = 'Titel';

$_COS_LANG_MODULE['Add Gallery'] = 'Nyt Galleri';
$_COS_LANG_MODULE['View Galleries'] = 'Vis Gallerier';

$_COS_LANG_MODULE['Gallery title should be at least 3 chars long'] =
    'Galleriet titel skal mindst være tre karakterer';

$_COS_LANG_MODULE['List Galleries'] = 'Vis Gallerier';
$_COS_LANG_MODULE['Delete current image Admin?'] = 
    'Slet nuværende billede?';
$_COS_LANG_MODULE['View and Delete image by image'] =
    'Vis og slet billeder';

$_COS_LANG_MODULE['Edit gallery name'] = 'Rediger galleri navn';
$_COS_LANG_MODULE['Delete entire gallery'] = 'Slet galleri';
$_COS_LANG_MODULE['View this gallery'] = 'Vis dette gallery';
$_COS_LANG_MODULE['Edit this gallery'] = 'Rediger dette galleri';
$_COS_LANG_MODULE['No file specified'] = 'Ingen fil specificeret';
$_COS_LANG_MODULE['Gallery updated'] = 'Galleri opdateret';

$_COS_LANG_MODULE['Edit Gallery'] = 'Rediger gallery';
$_COS_LANG_MODULE['View gallery'] = 'Vis galleri';
$_COS_LANG_MODULE['Gallery created'] = 'Nyt galleri oprettet';

$_COS_LANG_MODULE['Upload image'] = 'Upload Billed';

$_COS_LANG_MODULE['File seems to already exist. Only unique filenames allowed'] =
    'File eksisterer. Kun unikke filnavne er tilladte.';