<?php


// Translation of file /modules/gallery/install.inc

$_COS_LANG_MODULE['Gallery'] = 'Galleri';

// Translation of file /modules/gallery/admin/menu.inc

$_COS_LANG_MODULE['Add file'] = 'Nyt Galleri';

// Translation of file /modules/gallery/menu.inc

$_COS_LANG_MODULE['List galleries'] = 'Vis Gallerier';
$_COS_LANG_MODULE['Add gallery'] = 'Tilføj gallery';
$_COS_LANG_MODULE['Upload zip'] = 'Upload zip';
