<?php


// Translation of file /modules/gallery/tags.php

$_COS_LANG_MODULE['Gallery tag'] = 'Gallery tag';

// Translation of file /modules/gallery/module.php

$_COS_LANG_MODULE['View gallery'] = 'View gallery';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Upload image'] = 'Upload image';
$_COS_LANG_MODULE['File deleted'] = 'File deleted';
$_COS_LANG_MODULE['File is gallery default'] = 'File is gallery default';
$_COS_LANG_MODULE['File added'] = 'File added';
$_COS_LANG_MODULE['Could not rename file. File name already exists'] = 'Could not rename file. File name already exists';

// Translation of file /modules/gallery/delete.php

$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['File deleted'] = 'File deleted';

// Translation of file /modules/gallery/admin/module.php

$_COS_LANG_MODULE['Gallery title should be at least 3 chars long'] = 'Gallery title should be at least 3 chars long';
$_COS_LANG_MODULE['Edit files'] = 'Edit files';
$_COS_LANG_MODULE['Edit gallery'] = 'Edit gallery';
$_COS_LANG_MODULE['Delete gallery'] = 'Delete gallery';
$_COS_LANG_MODULE['Main image'] = 'Main image';
$_COS_LANG_MODULE['No title'] = 'No title';
$_COS_LANG_MODULE['Add file'] = 'Add file';
$_COS_LANG_MODULE['Set image details'] = 'Set image details';
$_COS_LANG_MODULE['File name'] = 'File name';

// Translation of file /modules/gallery/admin/delete.php

$_COS_LANG_MODULE['Delete gallery'] = 'Delete gallery';
$_COS_LANG_MODULE['Gallery has been deleted'] = 'Gallery has been deleted';

// Translation of file /modules/gallery/admin/edit.php

$_COS_LANG_MODULE['Edit gallery'] = 'Edit gallery';
$_COS_LANG_MODULE['Gallery updated'] = 'Gallery updated';

// Translation of file /modules/gallery/admin/index.php

$_COS_LANG_MODULE['Add file'] = 'Add file';
$_COS_LANG_MODULE['Gallery created'] = 'Gallery created';

// Translation of file /modules/gallery/upload/index.php

$_COS_LANG_MODULE['Upload zip file'] = 'Upload zip file';
$_COS_LANG_MODULE['Rename files after following title'] = 'Rename files after following title';
$_COS_LANG_MODULE['Could not move files'] = 'Could not move files';
$_COS_LANG_MODULE['Could not set correct permissions on files'] = 'Could not set correct permissions on files';
$_COS_LANG_MODULE['Could not rename files'] = 'Could not rename files';
$_COS_LANG_MODULE['Could not commit to database'] = 'Could not commit to database';
$_COS_LANG_MODULE['Zip archive uploaded'] = 'Zip archive uploaded';

// Translation of file /modules/gallery/inline/module.php

$_COS_LANG_MODULE['Large image'] = 'Large image';
$_COS_LANG_MODULE['Image details (exif)'] = 'Image details (exif)';
$_COS_LANG_MODULE['GPS'] = 'GPS';
$_COS_LANG_MODULE['Edit image details'] = 'Edit image details';
$_COS_LANG_MODULE['Original image'] = 'Original image';
$_COS_LANG_MODULE['Image details has been updated'] = 'Image details has been updated';

// Translation of file /modules/gallery/index.php

$_COS_LANG_MODULE['List galleries'] = 'List galleries';
