<?php

/**
 * language file for module simple
 * included when module is being used
 *
 * @package simple
 */

$_COS_LANG_MODULE['Select Gallery'] = 'Select Gallery';
$_COS_LANG_MODULE['Listing Galleries'] = 'Listing Galleries';
$_COS_LANG_MODULE['Add File'] = 'Add File';
$_COS_LANG_MODULE['Title'] = 'Title';

$_COS_LANG_MODULE['Add Gallery'] = 'Add Gallery';
$_COS_LANG_MODULE['View Galleries'] = 'View Galleries';

$_COS_LANG_MODULE['Gallery title should be at least 3 chars long'] =
    'Gallery title should be at least 3 chars long';

$_COS_LANG_MODULE['List Galleries'] = 'List Galleries';
$_COS_LANG_MODULE['Delete current image Admin?'] = 
    'Delete current image Admin?';
$_COS_LANG_MODULE['View and Delete image by image'] =
    'View and Delete image by image';

$_COS_LANG_MODULE['Edit gallery name'] = 'Edit gallery name';
$_COS_LANG_MODULE['Delete entire gallery'] = 'Delete entire gallery';
$_COS_LANG_MODULE['View this gallery'] = 'View this gallery';
$_COS_LANG_MODULE['Edit this gallery'] = 'Edit this gallery';
$_COS_LANG_MODULE['No file specified'] = 'No file specified';
$_COS_LANG_MODULE['Gallery updated'] = 'Gallery updated';

$_COS_LANG_MODULE['Edit Gallery'] = 'Edit Gallery';
$_COS_LANG_MODULE['View gallery'] = 'View gallery';

$_COS_LANG_MODULE['Gallery created'] = 'Gallery created';

$_COS_LANG_MODULE['Upload image'] = 'Upload image';
$_COS_LANG_MODULE['File seems to already exist. Only unique filenames allowed'] =
    'File seems to already exist. Only unique filenames allowed';
$_COS_LANG_MODULE['Edit gallery'] = 'Edit gallery';
$_COS_LANG_MODULE['gallery_edit_files'] = 'gallery_edit_files';
$_COS_LANG_MODULE['gallery_edit_name'] = 'gallery_edit_name';
$_COS_LANG_MODULE['Delete Gallery'] = 'Delete Gallery';
$_COS_LANG_MODULE['has been deleted'] = 'has been deleted';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['gallery_file_deleted'] = 'Fil Deleted';
$_COS_LANG_MODULE['gallery_file_added'] = 'File Added';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['File deleted'] = 'File deleted';
