<?php

/**
 * language file for module simple
 * included when module is being used
 *
 * @package simple
 */

$_COS_LANG_MODULE['Select Gallery'] = 'Select Gallery';
$_COS_LANG_MODULE['Listing Galleries'] = 'Listing Galleries';
$_COS_LANG_MODULE['Add File'] = 'Add File';
$_COS_LANG_MODULE['Title'] = 'Title';

$_COS_LANG_MODULE['Add Gallery'] = 'Add Gallery';
$_COS_LANG_MODULE['View Galleries'] = 'View Galleries';

$_COS_LANG_MODULE['Gallery title should be at least 3 chars long'] =
    'Gallery title should be at least 3 chars long';

$_COS_LANG_MODULE['List Galleries'] = 'List Galleries';
$_COS_LANG_MODULE['Delete current image Admin?'] = 
    'Delete current image Admin?';
$_COS_LANG_MODULE['View and Delete image by image'] =
    'View and Delete image by image';

$_COS_LANG_MODULE['Edit gallery name'] = 'Edit gallery name';
$_COS_LANG_MODULE['Delete entire gallery'] = 'Delete entire gallery';
$_COS_LANG_MODULE['View this gallery'] = 'View this gallery';
$_COS_LANG_MODULE['Edit this gallery'] = 'Edit this gallery';
$_COS_LANG_MODULE['No file specified'] = 'No file specified';
$_COS_LANG_MODULE['Gallery updated'] = 'Gallery updated';

$_COS_LANG_MODULE['Edit Gallery'] = 'Edit Gallery';
$_COS_LANG_MODULE['View gallery'] = 'View gallery';

$_COS_LANG_MODULE['Gallery created'] = 'Gallery created';

$_COS_LANG_MODULE['Upload image'] = 'Upload image';
$_COS_LANG_MODULE['File seems to already exist. Only unique filenames allowed'] =
    'File seems to already exist. Only unique filenames allowed';
$_COS_LANG_MODULE['Edit gallery'] = 'Edit gallery';
$_COS_LANG_MODULE['gallery_edit_files'] = 'Edit Files';
$_COS_LANG_MODULE['gallery_edit_name'] = 'Edit Gallery';
$_COS_LANG_MODULE['Delete Gallery'] = 'Delete Gallery';
$_COS_LANG_MODULE['has been deleted'] = 'has been deleted';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['gallery_file_deleted'] = 'Fil Deleted';
$_COS_LANG_MODULE['gallery_file_added'] = 'File Added';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['File deleted'] = 'File deleted';
$_COS_LANG_MODULE['gallery_default_image'] = 'Main Image';


$_COS_LANG_MODULE['gallery_form_label_path'] = 'Set A Path';
$_COS_LANG_MODULE['gallery_file_is_default'] = 'File is gallery default';

$_COS_LANG_MODULE['gallery_delete_has_files'] = 'Gallery has files. Delete all files before delting your gallery.';
$_COS_LANG_MODULE['gallery_gallery_has_been_deleted'] = 'Gallery has been deleted';
$_COS_LANG_MODULE['gallery_delete_legend'] = 'Delete gallery';
$_COS_LANG_MODULE['gallery_delete_gallery'] = 'Delete gallery';

$_COS_LANG_MODULE['gallery_upload_zip_legend'] = 'Upload zip file';
$_COS_LANG_MODULE['gallery_label_zip_add_chars'] = 'Rename files after following title';
$_COS_LANG_MODULE['gallery_error_zip_mv'] = 'Could not move files';
$_COS_LANG_MODULE['gallery_error_zip_chmod'] = 'Could not set correct permissions on files';
$_COS_LANG_MODULE['galler_error_unzip'] = 'Could not unzip';
$_COS_LANG_MODULE['gallery_zip_could_not_rename_file'] = 'Could not rename files';
$_COS_LANG_MODULE['gallery_zip_error_scale'] = 'Could not scale files';
$_COS_LANG_MODULE['gallery_zip_mv_error'] = 'Could not move files';
$_COS_LANG_MODULE['gallery_zip_commit_error'] = 'Could not commit to database';
$_COS_LANG_MODULE['gallery_zip_archive_uploaded'] = 'Zip archive uploaded';
$_COS_LANG_MODULE['gallery_set_image_details'] = 'Set image details';
$_COS_LANG_MODULE['gallery_file_name'] = 'File name';
$_COS_LANG_MODULE['gallery_view_full_size'] = 'Large image';
$_COS_LANG_MODULE['gallery_view_original_size'] = 'Original image';
$_COS_LANG_MODULE['gallery_image_details_updated'] = 'Image details has been updated';

$_COS_LANG_MODULE['gallery_tags_list_entries_title'] = 'Gallery tag';
$_COS_LANG_MODULE['gallery_could_not_rename_file_exists'] = 'Could not rename file. File name already exists';

$_COS_LANG_MODULE['gallery_edit_details'] = 'Edit image details';
$_COS_LANG_MODULE['gallery_view_exif'] = 'Image details (exif)';

$_COS_LANG_MODULE['gallery_view_gps'] = 'GPS';

$_COS_LANG_MODULE['gallery: title: no title'] = 'No title';
