<?php


// Translation of file /modules/gallery/admin/menu.inc

$_COS_LANG_MODULE['Add file'] = 'Add file';

// Translation of file /modules/gallery/install.inc

$_COS_LANG_MODULE['Gallery'] = 'Gallery';

// Translation of file /modules/gallery/menu.inc

$_COS_LANG_MODULE['List galleries'] = 'List galleries';
$_COS_LANG_MODULE['Add gallery'] = 'Add gallery';
$_COS_LANG_MODULE['Upload zip'] = 'Upload zip';
